USE [myCompany]
GO

/****** Object:  Table [dbo].[State]    Script Date: 2/26/2024 2:10:57 PM ******/
SET ANSI_NULLS ON
GO


IF OBJECT_ID(N'dbo.State',N'U') IS NOT NULL
DROP TABLE [dbo].[State]
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[State](
	[StateId] [int] IDENTITY(1,1) NOT NULL,
	[State] [varchar](50) NULL
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

